### PR TITLE
Add data tables to auto-generated docs

### PR DESCRIPTION
**Pull request by mike-solomon**
Fixes: https://github.com/openrewrite/rewrite-recipe-markdown-generator/issues/57

Here's an example of what a recipe doc with data tables looks like:

# Check for dependency vulnerabilities

**org.openrewrite.java.dependencies.DependencyVulnerabilityCheck**

_This is a software composition analysis (SCA) tool which detects publicly disclosed vulnerabilities. If vulnerabilities are found, it will generate a report linking to the associated CVE entries. Vulnerability information comes from the [GitHub Security Advisory Database](https://docs.github.com/en/code-security/security-advisories/global-security-advisories/about-the-github-advisory-database), which aggregates vulnerability data from several public databases, including the [National Vulnerability Database](https://nvd.nist.gov/) maintained by the United States government. Dependencies following [Semantic Versioning](https://semver.org/) will see their _patch_ version updated where applicable._

## Source

[GitHub](https://github.com/openrewrite/rewrite-java-dependencies/blob/main/src/main/java/org/openrewrite/java/dependencies/DependencyVulnerabilityCheck.java), [Issue Tracker](https://github.com/openrewrite/rewrite-java-dependencies/issues), [Maven Central](https://central.sonatype.com/artifact/org.openrewrite.recipe/rewrite-java-dependencies/1.0.1/jar)

* groupId: org.openrewrite.recipe
* artifactId: rewrite-java-dependencies
* version: 1.0.1

## Options

| Type | Name | Description |
| -- | -- | -- |
| `String` | scope | Match dependencies with the specified scope |
| `Boolean` | overrideManagedVersion | *Optional*. This flag can be set to explicitly override a managed dependency's version. The default for this flag is `false`. |
| `Boolean` | addMarkers | *Optional*. Report each vulnerability in search results. If this is off, it is easier to see suggested changes. |

### Vulnerability report

_Contains a vulnerability report the affected artifact and the vulnerability's CVE information._

| Column Name | Description |
| ----------- | ----------- |
| CVE | The CVE number. |
| Group | The first part of a dependency coordinate `com.google.guava:guava:VERSION`. |
| Artifact | The second part of a dependency coordinate `com.google.guava:guava:VERSION`. |
| Version | The resolved version. |
| Fixed in version | The minimum version that is no longer vulnerable. |
| Fixable with version update only | Whether the vulnerability is likely to be fixed by increasing the dependency version only, with no code modifications required. This is a heuristic which assumes that the dependency is accurately versioned according to [semver](https://semver.org/). |
| Summary | The summary of the CVE. |
| Base score | The calculated base score. |
| Depth | Zero for direct dependencies. |

## Usage

This recipe has required configuration parameters. Recipes with required configuration parameters cannot be activated directly. To activate this recipe you must create a new recipe which fills in the required parameters. In your `rewrite.yml` create a new recipe with a unique name. For example: `com.yourorg.DependencyVulnerabilityCheckExample`.
Here's how you can define and customize such a recipe within your rewrite.yml:

{% code title="rewrite.yml" %}
```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: com.yourorg.DependencyVulnerabilityCheckExample
displayName: Check for dependency vulnerabilities example
recipeList:
  - org.openrewrite.java.dependencies.DependencyVulnerabilityCheck:
      scope: compile
      overrideManagedVersion: false
      addMarkers: null
```
{% endcode %}

Now that `com.yourorg.DependencyVulnerabilityCheckExample` has been defined activate it and take a dependency on org.openrewrite.recipe:rewrite-java-dependencies:1.0.1 in your build file:
{% tabs %}
{% tab title="Gradle" %}
{% code title="build.gradle" %}
```groovy
plugins {
    id("org.openrewrite.rewrite") version("6.1.2")
}

rewrite {
    activeRecipe("com.yourorg.DependencyVulnerabilityCheckExample")
}

repositories {
    mavenCentral()
}

dependencies {
    rewrite("org.openrewrite.recipe:rewrite-java-dependencies:1.0.1")
}
```
{% endcode %}
{% endtab %}
{% tab title="Maven" %}
{% code title="pom.xml" %}
```markup
<project>
  <build>
    <plugins>
      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <version>5.2.1</version>
        <configuration>
          <activeRecipes>
            <recipe>com.yourorg.DependencyVulnerabilityCheckExample</recipe>
          </activeRecipes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-java-dependencies</artifactId>
            <version>1.0.1</version>
          </dependency>
        </dependencies>
      </plugin>
    </plugins>
  </build>
</project>
```
{% endcode %}
{% endtab %}
{% endtabs %}

## See how this recipe works across multiple open-source repositories

[Moderne Link Image](https://public.moderne.io/recipes/org.openrewrite.java.dependencies.DependencyVulnerabilityCheck)

The community edition of the Moderne platform enables you to easily run recipes across thousands of open-source repositories.

Please [contact Moderne](https://moderne.io/product) for more information about safely running the recipes on your own codebase in a private SaaS.

### CODE REVIEW

**Comment by timtebeek** [comment]
Promising start! My one concern is that this also includes the data tables that are present for _every_ run, such as `Recipe performance`. I don't think is worthwhile to report those on all 1000+ recipes, but also not sure how best to handle those otherwise. Maybe hide only those in a collapsible block? Open to other suggestions.

**Comment by sambsnyd** [comment]
Agree that we should not show the always-there data tables on every recipe

**Comment by mike-solomon** [comment]
👍 Since it sounds like we don’t want to show these - should I just filter out the data tables with names that match the common ones? Most recipes wouldn’t show any data tables at that point. Dunno if that’s okay or not. Could also just list the common ones as a bullet point or something.

**Comment by sambsnyd** [comment]
Most recipes have no data tables of their own, so it is correct not to display any

**Comment by mike-solomon** [comment]
@sambsnyd @timtebeek Updated to filter out the three common data tables I'm aware of. If there are any others I should filter out, please let me know.

**Review by timtebeek — APPROVED** [review]
Looks good to me! Here's one with a single data table now:
https://openrewrite.github.io/rewrite-recipe-markdown-generator/reference/recipes/java/dependencies/dependencyvulnerabilitycheck.html

**Pull request merged**
